version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './app:/var/www/api'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '16000:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - './app:/var/www/api'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
    frontend:
        build: docker/frontend
        working_dir: /frontend
        ports:
            - '16001:8080'
        volumes:
            - './frontend:/var/www/frontend'
        depends_on:
            - php-fpm
